version: '3'
services:
  backend:
    build: ./services/backend/app
    ports:
      - 8001:8000
    volumes:
      - ./services/backend/app:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
